/**
 *@作者 luckly
 *@创建日期 2021/3/22 14:28
 *@描述  所有依赖包的版本
 */
object LibraryVersions {
	const val constraintLayoutVersion = "1.1.3"
	const val alibabaARouterVersion = "1.4.0"
	const val alibabaARouterCompilerVersion = "1.2.1"
	const val alibabaFastjsonVersion = "1.1.71"
	const val multidexVersion = "2.0.0"
	const val materialVersion = "1.1.0"
	const val cardviewVersion = "1.0.0"
	const val appcompatVersion = "1.1.0"
	const val coreVersion = "1.2.0"
	const val testRunnerVersion = "1.1.0"
	const val recyclerviewVersion = "1.1.0"
	const val espressoVersion = "3.1.0"
	const val facebookStethoVersion = "1.5.0"
	const val gsonVersion = "2.8.0"
	const val glideVersion = "4.9.0"
	const val baseRecyclerViewAdapterHelperVersion = "2.9.34"
	const val rxBinding3Version = "3.0.0"
	const val retrofit2Version = "2.3.0"
	const val rxjava2Version = "2.1.11"
	const val rxjava2RxAndroidVersion = "2.0.2"
	const val rxLifecycle2Version = "2.2.2"
	const val okHttp3LoggingInterceptorVersion = "3.9.1"
	const val leakCanaryAndroidVersion = "1.5.4"
	const val greendaoVersion = "3.3.0"
	const val junitVersion = "4.12"
	const val immersionBarVersion = "3.0.0"
	const val googleAutoServiceVersion = "1.0-rc4"
	const val javaPoetVersion = "1.11.1"
	const val viseUtilsVersion = "1.1.0"
	const val smartRefreshLayoutVersion = "1.1.0"
	const val gifDrawableVersion = "1.2.19"
	const val advancedLuBanVersion = "1.3.2"
	const val multipleImageSelectVersion = "1.0.4"
	const val pickerViewVersion = "4.1.9"
	const val buglyCrashReportUpGradeVersion = "1.4.1"
	const val buglyNativeCrashReportVersion = "2.2.0"
	const val mockitoCoreVersion = "1.10.19"
	const val robolectricVersion = "3.0"
	const val supportAnnotationsVersion = "28.0.0"
	const val tencentTaiSDKVersion = "1.2.3.41"
	const val tinkerAndroidLibVersion = "1.9.9"
	const val gsyVideoPlayerVersion = "7.1.8"
	const val convenientBannerVersion = "2.1.5"
	const val qiyukfUnicornVersion = "5.7.0"
	const val sVGAPlayerVersion = "2.5.13"
	const val zxingCoreVersion = "3.3.3"
	const val umSdkVersion = "9.3.3"
	const val umSdkASmsVersion = "1.1.4"
	const val permissionXVersion = "1.4.0"
	const val annotationVersion = "1.1.0"
	const val walleLibraryVersion = "1.1.7"
	const val roundedImageViewVersion = "2.2.1"
	const val legacySupportV4Version = "1.0.0"
	const val verticalTabLayoutVersion = "1.2.5"
	const val badgeViewVersion = "1.1.3"
	const val exoplayerCoreVersion = "2.12.0"
	const val kotlinStdlibVersion = "1.4.10"
	const val danmakuFlameMasterVersion = "0.5.3"
	const val zxingAndroidEmbeddedVersion = "3.5.0"


}
